config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"

  get '/auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: 'sessions#failure', via: [:get, :post]

  delete '/logout', to: 'sessions#destroy'

  resources :posts, only: %i[edit update] 
  
  resources :posts, param: :slug, except: %i[edit update] do
    resources :comments

    member do
      patch :publish
      patch :draft
    end
  end

  resources :tags, param: :slug
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :comments
  
  scope :published, -> { where(is_private: false) }
  
  has_rich_text :content

  before_validation :create_slug, on: :create

  def to_param
    slug
  end

  validates :title, :slug, presence: true, uniqueness: true
  validates :short_description, presence: true
  
  private

  def create_slug
    return if self.title.nil?
    
    slug = self.title.parameterize
    if Post.find_by(slug: slug)
      self.slug = slug + "-" + SecureRandom.hex(6)
    else
      self.slug = slug
    end
  end
end
 

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts
  before_validation :create_slug, on: :create

  validates :name, :slug, presence: true, uniqueness: true

  private

  def create_slug
    return if self.name.nil?
    
    slug = self.name.parameterize
    if Tag.find_by(slug: slug)
      self.slug = slug + "-" + SecureRandom.hex(6)
    else
      self.slug = slug
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  enum :role, { user: 0, admin: 1, guest_writer: 2 }

  validates :email, presence: true, uniqueness: true

  def is_admin?
    self.admin?
  end

  def is_guest_writer?
    self.guest_writer?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post

  def index
    @post.comments.order(created_at: :desc)
  end

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new(comments_params.merge(user: current_user))
    @comment.valid?
    Rails.logger.error(@comment.errors)
    render :new, status: :unprocessable_entity and return unless @comment.save

    redirect_to({ controller: :posts, action: :show, slug: @post.slug }, notice: 'Comment added.')
  end

  private

  def comments_params
    params.require(:comment).permit(:content)
  end

  def find_post
    @post = Post.find_by(slug: params[:post_slug])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit draft publish update destroy]

  def index
    @posts = policy_scope(Post).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params.merge(user: current_user))
    render :new, status: :unprocessable_entity and return unless @post.save

    params[:post][:tags]&.split(',')&.map(&:strip)&.each do |tag|
      tag_obj = Tag.find_or_create_by!(name: tag)
      @post.tags << tag_obj unless @post.tags.exists?(tag_obj.id)
    end
    redirect_to({ action: :show, slug: @post.slug }, notice: 'Post saved as draft.')
  end

  def show; end

  def edit; end

  def update
    render :edit, status: :unprocessable_entity and return unless @post.update(posts_params)

    updated_tags = params[:post][:tags]&.split(',')&.map(&:strip)
    removed_tags = @post.tags.where('name not in (?)', updated_tags)
    @post.tags.delete(*removed_tags)
    params[:post][:tags]&.split(',')&.map(&:strip)&.each do |tag|
      tag_obj = Tag.find_or_create_by!(name: tag)
      @post.tags << tag_obj unless @post.tags.exists?(tag_obj.id)
    end
    redirect_to({ action: :show, slug: @post.slug }, notice: 'Post updated.') 
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Post deleted.'
    redirect_to posts_path
  end

  def draft
    @post.toggle!(:draft)

    redirect_to post_path(@post)
  end

  def publish
    @post.toggle!(:is_private)
    @post.update(published_at: Time.now) if !@post.is_private

    redirect_to post_path(@post)
  end

  private

  def posts_params
    params.require(:post).permit(:title, :content, :slug, :is_private, :draft, :short_description)
  end

  def find_post
    @post = Post.find_by(slug: params[:slug]) || Post.find(params[:id])
    authorize @post

  rescue ActiveRecord::RecordNotFound => e
    Rails.logger.error e.message
    Rails.logger.error e.backtrace.join("\n")
    redirect_to(posts_path, alert: 'Invalid Post Address. This post cannot be found.') and return false
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    if user = User.where(email: auth.info.email).first
      session[:user_id] = user.id
      redirect_to root_path, notice: "You've successfully logged in via #{auth.provider.titleize}."
    else
      redirect_to root_path, alert: 'Access denied. You are not authorized to log in.'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  def failure
    redirect_to root_path, alert: 'Unable to authenticate with third party service.'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_tag, only: %i[show edit update destroy]

  def index
    @tags = Tag.all
  end

  def show
   @posts = policy_scope(@tag).order(created_at: :desc )
  end

  def edit; end

  def update
    redirect_to({ action: :show, slug: @tag.slug }, notice: 'Tag updated.') and return if @tag.update(tags_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy    
    @tag.destroy
    flash[:notice] = 'Tag deleted'
    redirect_to tags_path
  end

  private

  def tags_params
    params.require(:tag).permit(:name, :slug)
  end

  def find_tag
    @tag = Tag.find_by(slug: params[:slug])
    raise ActiveRecord::RecordNotFound if @tag.nil?
    authorize @tag

  rescue ActiveRecord::RecordNotFound => e
    Rails.logger.error e.message
    Rails.logger.error e.backtrace.join("\n")
    redirect_to(tags_path, alert: 'Invalid Tag. This tag cannot be found.') and return false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    session.key?(:user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_form.html.erb
<div>
  <h1>Create new comment</h1>
  <%= form_with model: comment, url: post_comments_path(post_slug: @post.slug) do |form| %>
    <div>
      <%= form.label :content, "Content:" %><br>
      <%= form.text_area :content %>
    </div>
    <div>
      <%= form.submit  %>
    </div>
  <% end %>
</div>

app/views/comments/index.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
  <p><%= comment.content %></p>
  <p>by: <%= comment.user.email %></p>
  <hr>
<% end %>

app/views/comments/new.html.erb
<div>
  <h1>Create new comment</h1>
  <%= render partial: "form", locals: {comment: @comment} %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EminaDev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= link_to "Homepage", root_path %><br>
    <%= link_to "Tags", tags_path %><br>

    <% if logged_in? %>
      <%= link_to 'Logout', logout_path, data: { turbo_method: :delete } %>
    <% else %>
      <%= link_to 'Login with Google', '/auth/google_oauth2' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_errors.html.erb
<% if @post.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

  <ul>
    <% @post.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/posts/_form.html.erb
<div>
  <%= form.label :title, "Title:" %>
  <%= form.text_field :title %>
</div>
<div>
  <%= form.label :short_description, "Short description:" %><br>
  <%= form.text_area :short_description %>
</div>
<div>
  <%= form.label :content, "Content:" %><br>
  <%= form.rich_text_area :content %>
</div>
<div>
  <%= form.label :tags, "Tags:" %><br>
  <%= form.text_area :tags, value: @post.tags.map(&:name).join(', ') %>
</div>
<div>
  <%= form.submit  %>
</div>

app/views/posts/edit.html.erb
<div>
  <h1>Edit post</h1>
  <%= render partial: 'errors' %>
  
  <%= form_with model: @post, url: post_path(id: @post.id) do |form| %>
    <div>
      <%= form.label :slug, "Slug:" %>
      <%= form.text_field :slug %>
    </div>
    <%= render partial: 'form', locals: { form: form } %>
  <% end %>
</div>

app/views/posts/index.html.erb
<h1>blog dev</h1>
<% if policy(Post.new).update? %>
  <%= link_to 'Create new post', new_post_path %>
<% end %>

<% @posts.each do |post| %>
  <div>
    <h2><%= post.title %></h2>
    <i><%= post.short_description %></i><br><br>
    <%= link_to 'Read more', post_path(post) %>
    <p><%= post&.published_at&.strftime('%b %d, %Y') %></p>
    <p>Finished: <%= post.draft ? "No" : "Yes" %></p>
    <p>Published: <%= post.is_private ? "No" : "Yes" %></p>
    <p>
      Tags: 
      <% post.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(slug: tag.slug) %>
      <% end %>
    </p>
    <hr>
  </div>
<% end %>

app/views/posts/new.html.erb
<div>
  <h1>Create new post</h1>
  <%= render partial: 'errors' %>

  <%= form_with(model: @post) do |form| %>
  <%= render partial: 'form', locals: { form: form } %>
  <% end %>
</div>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<i><%= @post.short_description %></i><br><br>
<%= @post.content %><br>

<p>Finished: <%= @post.draft ? "No" : "Yes" %></p>
<p>Published: <%= @post.is_private ? "No" : "Yes" %></p>

<p>
  Tags: 
  <% @post.tags.each do |tag| %>
  <%= link_to tag.name, tag_path(slug: tag.slug) %>
  <% end %>
</p>

<% if policy(@post).edit? && @post.draft && @post.is_private %>
<%= link_to 'Edit', edit_post_path(id: @post.id) %>
|
<% end %>

<% if policy(@post).destroy? && @post.is_private %>
<%= link_to "Delete", post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<% end %>

<br><br>
<% if policy(@post).draft? && @post.draft && @post.is_private %>
  <%= link_to "Mark as completed", draft_post_path(slug: @post.slug), data: { turbo_method: :patch } %>
<% end %>

<% if policy(@post).draft? && !@post.draft && @post.is_private %>
  <%= link_to "Mark as draft", draft_post_path(slug: @post.slug), data: { turbo_method: :patch } %> 
<% end %>

<% if policy(@post).publish? && @post.is_private && !@post.draft %>
|
  <%= link_to "Publish", publish_post_path(slug: @post.slug), data: { turbo_method: :patch } %>
<% end %>

<% if policy(@post).publish? && !@post.is_private && !@post.draft %>
  <%= link_to "Mark as private", publish_post_path(slug: @post.slug), data: { turbo_method: :patch } %> 
<% end %>

<br><br>
<%= link_to 'comments#index', post_comments_path(post_slug: @post.slug) %>

<%= render partial: "comments/form", locals: {comment: Comment.new} %>

app/views/tags/edit.html.erb
<div>
  <h1>Edit tag</h1>

  <%= form_with model: @tag, url: tag_path(id: @tag.id) do |form| %>
    <div>
      <%= form.label :name, "Name:" %>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.label :slug, "Slug:" %>
      <%= form.text_field :slug %>
    </div>
    <div>
      <%= form.submit  %>
    </div>
  <% end %>
</div>

app/views/tags/index.html.erb
<% @tags.each do |tag| %>
  <p><%= link_to tag.name, tag_path(slug: tag.slug) %></p>
<% end %>

app/views/tags/show.html.erb
<% if policy(@tag).edit? %>
  <p><%= link_to "Edit", edit_tag_path(id: @tag.id) %></p>
<% end %>

<% if policy(@tag).destroy? %>
  <%= link_to "Delete", tag_path(slug: @tag.slug), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<% end %>

<% @posts.each do |post| %>
  <p>Tags:</p>
  <% post.tags.each do |tag| %>
    <u><%= tag.name %></u>
  <% end %> 
  <h2><%= post.title %></h2>
  <i><%= post.short_description %></i><br><br>
  <%= post.content %><br>

<% end %>